// Sourced from real YouTube playlists (verified by browsing each playlist directly
// and cross-checking titles against durations):
// - Hindi:   "Motivational & Workout songs Hindi" (Kashyap Makadia) +
//            "Best Bollywood Workout Songs" (Redlist - Indian Charts)
// - English: "Hip-Hop Workout Music Playlist" (Redlist - Energy Playlists)
// - Phonk:   "Popular Phonk Songs / Top 50 Phonk Songs" (Gloamed Records)
// Swap any entry below for your own picks the same way -- videoId is the
// "v=" part of any YouTube URL.

const DEFAULT_GENRE = "phonk";

const PLAYLISTS = {
  hindi: {
    label: "Hindi",
    url: "https://www.youtube.com/playlist?list=PLWd4gmX2j6dOUpWveHdipQ-vqlPX1A0f1",
    tracks: [
      { title: "Zinda", artist: "Bhaag Milkha Bhaag • Farhan Akhtar", videoId: "Ax0G_P2dSBw" },
      { title: "Jai Ho", artist: "Slumdog Millionaire • A.R. Rahman", videoId: "xwwAVRyNmgQ" },
      { title: "Chale Chalo", artist: "Lagaan • A.R. Rahman", videoId: "LQmHKl3oNu0" },
      { title: "Brothers Anthem", artist: "Brothers • Vishal Dadlani", videoId: "IjBAgWKW12Y" },
      { title: "Sultan (Title Song)", artist: "Sultan • Sukhwinder Singh", videoId: "abiL84EAWSY" },
      { title: "Chak Lein De", artist: "Chandni Chowk To China • Kailash Kher", videoId: "kd-6aw99DpA" },
      { title: "Ziddi Dil", artist: "Mary Kom • Vishal Dadlani", videoId: "puKD3nkB1h4" },
      { title: "Lakshya (Title Track)", artist: "Lakshya • Shankar-Ehsaan-Loy", videoId: "8DMF0U6xV78" },
      { title: "Sadda Haq", artist: "Rockstar • Mohit Chauhan", videoId: "p9DQINKZxWE" },
      { title: "Dangal (Title Track)", artist: "Dangal • Daler Mehndi", videoId: "91ZI3IrojMU" },
      { title: "Chak De India (Title Song)", artist: "Chak De India • Sukhvinder Singh", videoId: "080YTN2tE7I" },
      { title: "Soorma Anthem", artist: "Soorma • Diljit Dosanjh", videoId: "UXARxGUMfsk" },
      { title: "Le Le Maza Le", artist: "Wanted • Sajid-Wajid", videoId: "Q7kv9nuhTB8" },
      { title: "Bam Bam Bhole", artist: "Sikandar • Pritam", videoId: "INSOyREDJ7k" },
      { title: "Kar Har Maidaan Fateh", artist: "Sanju • Sukhwinder Singh, Shreya Ghoshal", videoId: "9iIX4PBplAY" },
      { title: "Malhari", artist: "Bajirao Mastani • Vishal Dadlani", videoId: "l_MyUGq7pgs" },
      { title: "Apna Time Aayega", artist: "Gully Boy • DIVINE", videoId: "jFGKJBPFdUA" },
      { title: "Azadi", artist: "Gully Boy • DIVINE", videoId: "4nCshJBODT4" },
      { title: "Rang De Basanti (Title Track)", artist: "Rang De Basanti • A.R. Rahman, Daler Mehndi", videoId: "c769V25pX08" },
      { title: "Khalbali", artist: "Rang De Basanti • A.R. Rahman", videoId: "hnswwRWLi3E" },
      { title: "Get Ready To Fight", artist: "Baaghi • Benny Dayal", videoId: "h6aGikIL-I4" },
      { title: "Sachin Sachin", artist: "Sachin: A Billion Dreams • A.R. Rahman", videoId: "Kvp9L72COMA" },
      { title: "Chak De Phattey", artist: "Khosla Ka Ghosla! • Kailash Kher", videoId: "gz00gYCzkMU" },
      { title: "Malang (Title Track)", artist: "Malang • Ved Sharma", videoId: "KBIq11mNB0I" },
      { title: "Zor Ka Jhatka", artist: "Action Replayy • Daler Mehndi", videoId: "mXhYUmv1yZg" },
      { title: "Zinda Banda", artist: "Jawan • Anirudh Ravichander", videoId: "stjZKBhQ3lg" },
      { title: "Jhoome Jo Pathaan", artist: "Pathaan • Arijit Singh", videoId: "YxWlaYCA8MU" },
      { title: "Naacho Naacho", artist: "RRR • M.M. Keeravaani", videoId: "sAzlWScHTc4" },
      { title: "Khalibali", artist: "Padmaavat • Shivam Pathak", videoId: "v7K4vGYL9zI" },
      { title: "Mere Gully Mein", artist: "Gully Boy • DIVINE, Naezy", videoId: "pGmbUdf6lEM" },
      { title: "Asli Hip Hop (Spitfire)", artist: "Gully Boy • Ranveer Singh", videoId: "U39GgfIgtn8" },
      { title: "Swag Se Swagat", artist: "Tiger Zinda Hai • Vishal Dadlani, Neha Bhasin", videoId: "xB3iI-LH9Ak" },
      { title: "Aata Majhi Satakli", artist: "Singham Returns • Yo Yo Honey Singh", videoId: "M3KqzpP6Ej0" },
      { title: "Main Hoon Don", artist: "Don • Shaan", videoId: "BcKDqv_9A58" },
      { title: "Allah Duhai Hai", artist: "Race 3 • JAM8", videoId: "Gop2g29j70Q" },
      { title: "Toofaan (Title Track)", artist: "Toofaan • Shankar-Ehsaan-Loy", videoId: "E8Fh5gkUdI8" },
      { title: "Todun Taak", artist: "Toofaan • D'Evil, Dub Sharma", videoId: "Ee228eqx3RY" },
      { title: "Get Ready To Fight Again", artist: "Baaghi 2 • Tiger Shroff", videoId: "zLVZxHWL0ro" },
      { title: "Maston Ka Jhund", artist: "Bhaag Milkha Bhaag • Divya Kumar", videoId: "yWeVII7qF3A" },
      { title: "Bang Bang (Title Track)", artist: "Bang Bang! • Vishal-Shekhar, Benny Dayal", videoId: "jZyAB2KFDls" },
    ],
  },
  phonk: {
    label: "Phonk",
    url: "https://www.youtube.com/playlist?list=PLp-YgLPmqeo7S1ZQw4ECI4-ybGwHKdLkb",
    tracks: [
      { title: "Murder Plot", artist: "KORDHELL", videoId: "_c2NS5Om998" },
      { title: "Murder In My Mind", artist: "KORDHELL", videoId: "mzD50zVl20E" },
      { title: "MISA MISA!", artist: "CORPSE", videoId: "1I9cI53az7E" },
      { title: "Shake It", artist: "Phonku", videoId: "5BTItda4l_w" },
      { title: "Massacre", artist: "SHADXWBXRN", videoId: "-5TgcaaTbn8" },
      { title: "The Unspeakable", artist: "Phonked", videoId: "qfU1B7OGlBc" },
      { title: "Miss Me?", artist: "scarlxrd & kordhell", videoId: "aYtOKQ9LYYQ" },
      { title: "Soca Sem Parar", artist: "KUTE", videoId: "qzWK7YxJ6lM" },
      { title: "Going Crazy", artist: "Kardanas", videoId: "cbhQPvw9a5c" },
      { title: "Phonky Tribu", artist: "Funk Tribu", videoId: "exI40Lqyd0k" },
      { title: "Boss Of The Pirates", artist: "Phonku", videoId: "2uwCU3ptBwk" },
      { title: "I'm Good (Blue) (RAIZHELL Remix)", artist: "David Guetta, Bebe Rexha", videoId: "ifZ63hf64r8" },
      { title: "Bring Me Back To Life", artist: "Phonku", videoId: "HMgq1R0XYGM" },
      { title: "Ease Off (Twisted Phonk Remix)", artist: "YNG Martyr", videoId: "L_BB5twSqAc" },
      { title: "Victimize", artist: "Phonku", videoId: "63dJrnHFr0U" },
      { title: "Metamorphosis", artist: "INTERWORLD", videoId: "lJvRohYSrZM" },
      { title: "Rave", artist: "Dxrk ダーク", videoId: "PTZgxW_3LIQ" },
      { title: "Final Boss Fight!", artist: "Phonku", videoId: "t-EVg9STn-M" },
      { title: "Neon Blade", artist: "MoonDeity", videoId: "dvQJIgjlR3I" },
      { title: "GigaChad Theme (Phonk House Version)", artist: "g3ox_em", videoId: "OVh0bMNSFss" },
      { title: "Adrenaline", artist: "Phonku", videoId: "kzwdOb6RpHs" },
      { title: "Close Eyes", artist: "DVRST", videoId: "ao4RCon11eY" },
      { title: "Make You Scream", artist: "Phonked", videoId: "iTVlSmw0VnM" },
      { title: "Prince Of Darkness", artist: "SHADXWBXRN, ARCHEZ, KXNVRA", videoId: "aEYnGzD942o" },
      { title: "Afterlife", artist: "TWISTED & TEARZ", videoId: "wGN411Mqh0Q" },
      { title: "Avoid Me 3", artist: "KUTE", videoId: "l0LjoqTaVt4" },
      { title: "Lithuanian Phonk", artist: "Phonku", videoId: "xtVqfvfyla0" },
      { title: "Step Back!", artist: "1nonly & SXMPRA", videoId: "E4GHq_yP-ro" },
      { title: "Blood Thirst", artist: "Phonku", videoId: "Z8IkFAQYM94" },
      { title: "Midnight", artist: "PLAYAMANE x Nateki", videoId: "iBv6kB7WxYg" },
      { title: "Flare", artist: "Hensonn", videoId: "G9CVOSRkxUs" },
      { title: "Sahara", artist: "Hensonn", videoId: "pIZ0QRWK0zg" },
      { title: "Shadow", artist: "ONIMXRU x SMITHMANE", videoId: "jqbSVBS1x0w" },
      { title: "Anubis", artist: "KUTE x RAIZHELL", videoId: "nbC3r0W6GrI" },
      { title: "Why Not", artist: "Ghostface Playa", videoId: "Hh5jEQraXaw" },
    ],
  },
  english: {
    label: "English",
    url: "https://www.youtube.com/playlist?list=PLChOO_ZAB22WAvnFw86vUueyv026ULwIv",
    tracks: [
      { title: "In Da Club", artist: "50 Cent", videoId: "5qm8PH4xAss" },
      { title: "Without Me", artist: "Eminem", videoId: "tqxRidAWER8" },
      { title: "Low", artist: "Flo Rida ft. T-Pain", videoId: "U2waT9TxPU0" },
      { title: "Lose Yourself", artist: "Eminem", videoId: "_Yhyp-_hX2s" },
      { title: "Still D.R.E.", artist: "Dr. Dre", videoId: "Qeem6ZVr8Ic" },
      { title: "Taste", artist: "Tyga ft. Offset", videoId: "LjxulQ1bEWg" },
      { title: "Not Like Us", artist: "Kendrick Lamar", videoId: "T6eK-2OQtew" },
      { title: "The Box", artist: "Roddy Ricch", videoId: "4QGqFfhKWYo" },
      { title: "Not Afraid", artist: "Eminem", videoId: "-grPV-Fae6I" },
      { title: "FDO", artist: "Pooh Shiesty", videoId: "VASXcKzkB6Q" },
      { title: "SICKO MODE", artist: "Travis Scott ft. Drake", videoId: "6ONRf7h3Mdk" },
      { title: "The Next Episode", artist: "Dr. Dre ft. Snoop Dogg", videoId: "QZXc39hT8t4" },
      { title: "Praise The Lord (Da Shine)", artist: "A$AP Rocky ft. Skepta", videoId: "Kbj2Zss-5GY" },
      { title: "HUMBLE.", artist: "Kendrick Lamar", videoId: "tvTRZJ-4EyI" },
      { title: "A Lot", artist: "21 Savage", videoId: "VbrEsOLu75c" },
      { title: "Mask Off", artist: "Future", videoId: "AMCwYdTJ_PE" },
      { title: "Dior", artist: "Pop Smoke", videoId: "9dPiZwLnAMY" },
      { title: "Can't Hold Us", artist: "Macklemore ft. Ray Dalton", videoId: "96L5sV7rqX0" },
      { title: "Till I Collapse", artist: "Eminem", videoId: "Obim8BYGnOE" },
      { title: "Bad And Boujee", artist: "Migos ft. Lil Uzi Vert", videoId: "S-sJp1FfG7Q" },
      { title: "Ice Ice Baby", artist: "Vanilla Ice", videoId: "rog8ou-ZepE" },
      { title: "U Can't Touch This", artist: "MC Hammer", videoId: "gDCRrvtY78g" },
      { title: "Life Is Good", artist: "Future ft. Drake", videoId: "ZBOoVj6IW3s" },
      { title: "Rap God", artist: "Eminem", videoId: "XbGs_qK2PQA" },
      { title: "Super Gremlin", artist: "Kodak Black", videoId: "kiB9qk4gnt4" },
      { title: "Panda", artist: "Desiigner", videoId: "E5ONTXHS2mM" },
      { title: "Stronger", artist: "Kanye West", videoId: "PsO6ZnUZI0g" },
      { title: "Industry Baby", artist: "Lil Nas X ft. Jack Harlow", videoId: "4aNUdvctOok" },
      { title: "Back In Blood", artist: "Pooh Shiesty ft. Lil Durk", videoId: "0-Tm65i96TY" },
      { title: "Bodak Yellow", artist: "Cardi B", videoId: "PEGccV-NOm8" },
    ],
  },
};
